### ISSUE TITLE
Ambiguous use of operators

### ISSUE THREAD

**Issue by zezeron** [VideoFlint/Cabbage#2]
i use it XCODE10 beta 4 

23 error and not build this project. Ambiguous use of operator '+', '-', '==' etc.
<img width="1480" alt="screen shot 2018-08-03 at 13 14 40" src="https://user-images.githubusercontent.com/1241517/43637874-369e428e-971f-11e8-914a-95f8705b5b4c.png">
-fyi

**Comment by vitoziv** [comment]
I create a branch [Xcode10-build](https://github.com/VideoFlint/Cabbage/tree/Xcode10-build), fix the errors, and using swift 4.2.

I will merge it to master later, currently, you may use  [Xcode10-build](https://github.com/VideoFlint/Cabbage/tree/Xcode10-build) to try Cabbage.

**Comment by zezeron** [comment]
👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻😍
