### ISSUE TITLE
更改 track 的 timeRange 后如何实时应用到 playerItem 中呢？

### ISSUE THREAD

**Issue by Roxasora** [VideoFlint/Cabbage#22]

**Comment by vitoziv** [comment]
重新生成一下 `AVAsset` `AVVideoComposition` 和 `AVAudioMix`

**Comment by Roxasora** [comment]
目前确实是用这个办法，这样会不会有什么额外的问题呢，比方说剪辑timeline的时候频繁拖动VITimelineView的range，那 assetr，composition，mix都要频繁的重新生成吗？

**Comment by vitoziv** [comment]
是的，拖动手势结束的时候都要重新生成。

没什么问题

**Comment by Roxasora** [comment]
哈哈哈那我就这样用了，总觉得这样好奇怪哦！感谢指点！
