### ISSUE TITLE
倒放支持

### ISSUE THREAD

**Issue by vitoziv** [VideoFlint/Cabbage#6]
实时倒放技术探索。

**Comment by vitoziv** [comment]
目前没有看到合适的实时倒放技术实现，做实时倒放涉及两个问题：视频画面帧的实时倒放解码问题，音频倒放的播放问题。

目前 AVPlayer 可以通过设置 rate=-1 达到倒放的效果，但是还没有看到 iOS 有哪个 API 开放出了倒放的实时处理与合成。

难道真的只能进行预合成为倒放视频了吗？😿

**Comment by vitoziv** [comment]
可以使用 AVAssetReader 分片预解码的方式做到

**Comment by hellodevbaby** [comment]
> 可以使用 AVAssetReader 分片预解码的方式做到
你好，请教下音频倒放如何实现，可否给些思路，多谢！盼回复
